import { Routes } from '@angular/router';
import { NotFoundComponent } from './not-found/not-found.component';
import { HealthComponent } from './health/health.component';
import { HomeComponent } from './home/home.component';
import { CartComponent } from './cart/cart.component';
import { FitnessComponent } from './fitness/fitness.component';
import { NutritionComponent } from './nutrition/nutrition.component';
import { SignInComponent } from './sign-in/sign-in.component';
import { SubscribeComponent } from './subscribe/subscribe.component';
import { SignUpComponent } from './sign-up/sign-up.component';
import { MyReviewsComponent } from './my-reviews/my-reviews.component';
//Health Sections Details
import { BrainHealth1Component } from './health/brain-health-1/brain-health-1.component';
import { BrainHealth2Component } from './health/brain-health-2/brain-health-2.component';
import { BrainHealth3Component } from './health/brain-health-3/brain-health-3.component';
import { BrainHealth4Component } from './health/brain-health-4/brain-health-4.component';
import { BrainHealth5Component } from './health/brain-health-5/brain-health-5.component';
import { BrainHealth6Component } from './health/brain-health-6/brain-health-6.component';
import { HeartHealth1Component } from './health/heart-health-1/heart-health-1.component';
import { HeartHealth2Component } from './health/heart-health-2/heart-health-2.component';
import { HeartHealth3Component } from './health/heart-health-3/heart-health-3.component';
import { HeartHealth4Component } from './health/heart-health-4/heart-health-4.component';
import { HeartHealth5Component } from './health/heart-health-5/heart-health-5.component';
import { HeartHealth6Component } from './health/heart-health-6/heart-health-6.component';
import { BetterSleep1Component } from './health/better-sleep-1/better-sleep-1.component';
import { BetterSleep2Component } from './health/better-sleep-2/better-sleep-2.component';
import { BetterSleep3Component } from './health/better-sleep-3/better-sleep-3.component';
import { BetterSleep4Component } from './health/better-sleep-4/better-sleep-4.component';
import { UserHomeComponent } from './user-home/user-home.component';
import { ProfileComponent } from './profile/profile.component';
import { UpdatePasswordComponent } from './update-password/update-password.component';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { DietPlanComponent } from './nutrition/diet-plan/diet-plan.component';
import { MyDietPlanComponent } from './nutrition/my-diet-plan/my-diet-plan.component';
import { AdminComponent } from './admin-dashboard/admin-dashboard.component';
import { AdminUsersComponent } from './admin-users/admin-users.component';
import { AdminDietsComponent } from './admin-diets/admin-diets.component';
import { AdminRequestsComponent } from './admin-requests/admin-requests.component';
import { UserChatComponent } from './user-chat/user-chat.component';
import { AdminChatComponent } from './admin-chat/admin-chat.component';
import { ContactUsComponent } from './contact-us/contact-us.component';
import { ExercisePlanComponent } from './fitness/exercise-plan/exercise-plan.component';
import { MyExercisePlanComponent } from './fitness/my-exercise-plan/my-exercise-plan.component';
import { AdminExerciseComponent } from './admin-exercise/admin-exercise.component';
import { NotificationsComponent } from './notifications/notifications.component';
import { HEALTHYMEALSComponent } from './nutrition/information/healthy-meals/healthy-meals.component';
import { DIETS1Component } from './nutrition/information/diets1/diets1.component';
import { DIETS2Component } from './nutrition/information/diets2/diets2.component';
import { DIETS3Component } from './nutrition/information/diets3/diets3.component';
import { DIETS4Component } from './nutrition/information/diets4/diets4.component';
import { HEALTHYRECIPES1Component } from './nutrition/information/healthy-recipes1/healthy-recipes1.component';
import { HEALTHYRECIPES2Component } from './nutrition/information/healthy-recipes2/healthy-recipes2.component';
import { HEALTHYRECIPES3Component } from './nutrition/information/healthy-recipes3/healthy-recipes3.component';
import { HEALTHYRECIPES4Component } from './nutrition/information/healthy-recipes4/healthy-recipes4.component';
import { STRENGTHTRAINING1Component } from './fitness/fitnessComponents/strength-training1/strength-training1.component';
import { STRENGTHTRAINING2Component } from './fitness/fitnessComponents/strength-training2/strength-training2.component';
import { STRENGTHTRAINING3Component } from './fitness/fitnessComponents/strength-training3/strength-training3.component';
import { STRENGTHTRAINING4Component } from './fitness/fitnessComponents/strength-training4/strength-training4.component';
import { CARDIOFITNESS1Component } from './fitness/fitnessComponents/cardio-fitness1/cardio-fitness1.component';
import { CARDIOFITNESS2Component } from './fitness/fitnessComponents/cardio-fitness2/cardio-fitness2.component';
import { CARDIOFITNESS3Component } from './fitness/fitnessComponents/cardio-fitness3/cardio-fitness3.component';
import { CARDIOFITNESS4Component } from './fitness/fitnessComponents/cardio-fitness4/cardio-fitness4.component';
import { CARDIOFITNESS5Component } from './fitness/fitnessComponents/cardio-fitness5/cardio-fitness5.component';
import { CARDIOFITNESS6Component } from './fitness/fitnessComponents/cardio-fitness6/cardio-fitness6.component';
import { vipSubComponent } from './vip-sub/vip-sub.component';
import { CardAddComponent } from './card-add/card-add.component';
import { AdminReviewsComponent } from './admin-reviews/admin-reviews.component';
import { ExePicsComponent } from './fitness/exe-pics/exe-pics.component';

export const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', component: HomeComponent },
  { path: 'health', component: HealthComponent },
  { path: 'fitness', component: FitnessComponent },
  { path: 'exercise-plan', component: ExercisePlanComponent },
  { path: 'my-exercise-plan', component: MyExercisePlanComponent },
  { path: 'strength-training1', component: STRENGTHTRAINING1Component },
  { path: 'strength-training2', component: STRENGTHTRAINING2Component },
  { path: 'strength-training3', component: STRENGTHTRAINING3Component },
  { path: 'strength-training4', component: STRENGTHTRAINING4Component },
  { path: 'CARDIO-FITNESS1', component: CARDIOFITNESS1Component },
  { path: 'CARDIO-FITNESS2', component: CARDIOFITNESS2Component },
  { path: 'CARDIO-FITNESS3', component: CARDIOFITNESS3Component },
  { path: 'CARDIO-FITNESS4', component: CARDIOFITNESS4Component },
  { path: 'CARDIO-FITNESS5', component: CARDIOFITNESS5Component },
  { path: 'CARDIO-FITNESS6', component: CARDIOFITNESS6Component },
  { path: 'nutrition', component: NutritionComponent },
  { path: 'diet-plan', component: DietPlanComponent },
  { path: 'my-dietPlan', component: MyDietPlanComponent },
  { path: 'healthy-meals', component: HEALTHYMEALSComponent },
  { path: 'diets1', component: DIETS1Component },
  { path: 'diets2', component: DIETS2Component },
  { path: 'diets3', component: DIETS3Component },
  { path: 'diets4', component: DIETS4Component },
  { path: 'healthy-recips1', component: HEALTHYRECIPES1Component },
  { path: 'healthy-recips2', component: HEALTHYRECIPES2Component },
  { path: 'healthy-recips3', component: HEALTHYRECIPES3Component },
  { path: 'healthy-recips4', component: HEALTHYRECIPES4Component },
  { path: 'sign-in', component: SignInComponent },
  { path: 'subscribe', component: SubscribeComponent },
  { path: 'subscribe-pay', component: vipSubComponent },
  { path: 'card-add', component: CardAddComponent },
  { path: 'cart', component: CartComponent },
  { path: 'sign-up', component: SignUpComponent },
  { path: 'brain-health-1', component: BrainHealth1Component },
  { path: 'brain-health-2', component: BrainHealth2Component },
  { path: 'brain-health-3', component: BrainHealth3Component },
  { path: 'brain-health-4', component: BrainHealth4Component },
  { path: 'brain-health-5', component: BrainHealth5Component },
  { path: 'brain-health-6', component: BrainHealth6Component },
  { path: 'heart-health-1', component: HeartHealth1Component },
  { path: 'heart-health-2', component: HeartHealth2Component },
  { path: 'heart-health-3', component: HeartHealth3Component },
  { path: 'heart-health-4', component: HeartHealth4Component },
  { path: 'heart-health-5', component: HeartHealth5Component },
  { path: 'heart-health-6', component: HeartHealth6Component },
  { path: 'better-sleep-1', component: BetterSleep1Component },
  { path: 'better-sleep-2', component: BetterSleep2Component },
  { path: 'better-sleep-3', component: BetterSleep3Component },
  { path: 'better-sleep-4', component: BetterSleep4Component },
  { path: 'admin-dashboard', component: AdminComponent },
  { path: 'admin-users', component: AdminUsersComponent },
  { path: 'admin-reviews', component: AdminReviewsComponent },
  { path: 'admin-diets', component: AdminDietsComponent },
  { path: 'admin-exercise', component: AdminExerciseComponent },
  { path: 'admin-requests', component: AdminRequestsComponent },
  { path: 'admin-chat/:email', component: AdminChatComponent },
  { path: 'user-home', component: UserHomeComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'my-reviews', component: MyReviewsComponent },
  { path: 'update-password', component: UpdatePasswordComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'user-chat', component: UserChatComponent },
  { path: 'contact', component: ContactUsComponent },
  { path: 'notifications', component: NotificationsComponent },
  { path: 'exePics' , component : ExePicsComponent},
  { path: '**', component: NotFoundComponent },
];
